# .streamlit/secrets.toml
SUPABASE_URL = "https://cmodrzmjjsbndgjdptgs.supabase.co"  # 아까 복사한 주소
SUPABASE_KEY = "sb_publishable_MnX39kL2HT9GLYUREX_r6g_0bF2hHc7"                         # 아까 복사한 anon public 키